"""Initial migration

Revision ID: 737de56fb70f
Revises: 3c2b9f2fad59
Create Date: 2025-10-11 12:51:04.354715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '737de56fb70f'
down_revision = '3c2b9f2fad59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), nullable=False),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('is_published', sa.BOOLEAN(), nullable=True),
    sa.Column('pub_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
